#############################################################################
# Initialization settings
#############################################################################

/control/verbose 0
/run/verbose 0

/Mustard/Detector/Description/Ixport SimTTC/SimTTC.yaml

/MACE/Physics/DisableMuonMinusCapture

/MACE/Physics/UseOpticalPhysics
/run/initialize
/process/optical/scintillation/setFiniteRiseTime true

/MACE/Generator/SwitchToGPSX
/gps/particle                         mu-
/gps/pos/type                         Point
/gps/pos/centre                       0 0 0 m
/gps/ang/type                         iso
/gps/ene/mono                         0 MeV

/MACE/Analysis/SaveTTCHitData         yes
/MACE/Analysis/SaveTTCSiPMHitData     yes

#############################################################################
# Run
#############################################################################

/Mustard/Analysis/FilePath SimTTC_mum_decay.root
/Mustard/Analysis/FileMode NEW
/run/beamOn 10000
/Mustard/Run/PrintRunSummary
