/control/verbose 0
/run/verbose 0

#/Mustard/Detector/Description/Ixport SimMACE_geom.yaml

/run/initialize

/Mustard/Physics/MuonDecay/ICDecay/MetropolisDelta      0.005
/Mustard/Physics/MuonDecay/ICDecay/MetropolisDiscard    10
/MACE/Physics/MuonDecay/ICDecay/ApplyMACEBias           yes

# Estimate weight normalization factor with 1000*n samples
/Mustard/Physics/MuonDecay/ICDecay/EstimateWeightNormalizationFactor MuonICDecay mu+ 1000000
