#############################################################################
# Initialization settings
#############################################################################

/control/verbose 0
/run/verbose 0

#/Mustard/Detector/Description/Ixport SimMACE_geom.yaml

/run/initialize

/gps/particle             mu+
/gps/direction            0 0 1        # 0 deg
/gps/pos/centre           0 0 -1 m     # 0 deg
/gps/pos/type             Beam
/gps/pos/shape            Circle
/gps/pos/radius           0 mm
/gps/pos/sigma_r          5 mm
/gps/ene/type             Gauss
# CiADS full-solenoid focusing beam, 0.5-mA-proton beam on C target
/gps/ene/mono             3.346 MeV    # momentum 26.8 MeV
/gps/ene/sigma            0.393 MeV    # momentum spreading 1.6 MeV
## CiADS solenoid + QM focusing beam, 0.5-mA-proton beam on C target
#/gps/ene/mono             3.248 MeV    # momentum 26.4 MeV
#/gps/ene/sigma            0.339 MeV    # momentum spreading 1.4 MeV
/GPSX/NVertex             1
/GPSX/PulseWidth          1.5 us

/Mustard/Physics/MuoniumPhysics/Formation/ConversionProbability    1

/MACE/Physics/ApplyProductionCutNearTarget                         yes

/MACE/Analysis/SavePrimaryVertexData  yes
/MACE/Analysis/SaveDecayVertexData    yes
/MACE/Analysis/CoincidenceWithMMS     yes
/MACE/Analysis/CoincidenceWithMCP     yes
/MACE/Analysis/CoincidenceWithECAL    yes
/MACE/Analysis/SaveTTCHitData         yes
/MACE/Analysis/SaveCDCHitData         yes

#############################################################################
# Run
#############################################################################

/Mustard/Analysis/FilePath SimMACE_signal_test.root
/Mustard/Analysis/FileMode NEW
#/run/beamOn 8000

/run/beamOn 1000000

/Mustard/Run/PrintRunSummary
