#############################################################################
# Initialization settings
#############################################################################

/control/verbose 0
/run/verbose 0

#/Mustard/Detector/Description/Ixport SimMACE_geom.yaml

/run/initialize

/gps/particle             mu+
/gps/direction            0 0 1        # 0 deg
/gps/pos/centre           0 0 -1 m     # 0 deg
/gps/pos/type             Beam
/gps/pos/shape            Circle
/gps/pos/radius           0 mm
/gps/pos/sigma_r          5 mm
/gps/ene/type             Gauss
/gps/ene/mono             3.224 MeV    # momentum 26.3 MeV
/gps/ene/sigma            0.459 MeV    # momentum spreading 1.9 MeV
/GPSX/NVertex             10
/GPSX/PulseWidth          1.5 us

/Mustard/Physics/MuonDecay/ICDecay/BR                      1
/Mustard/Physics/MuonDecay/ICDecay/MetropolisDelta         0.001
/Mustard/Physics/MuonDecay/ICDecay/MetropolisDiscard       100000
/Mustard/Physics/MuonDecay/RadiativeDecay/BR                0
/Mustard/Physics/MuonDecay/UpdateDecayBR

/Mustard/Physics/MuoniumPhysics/Formation/ConversionProbability    0

/MACE/Physics/ApplyProductionCutNearTarget                         yes

/MACE/Analysis/SavePrimaryVertexData  yes
/MACE/Analysis/SaveDecayVertexData    yes
/MACE/Analysis/CoincidenceWithMMS     yes
/MACE/Analysis/CoincidenceWithMCP     yes
/MACE/Analysis/CoincidenceWithECAL    yes
/MACE/Analysis/SaveTTCHitData         yes
/MACE/Analysis/SaveCDCHitData         yes

#############################################################################
# Run
#############################################################################

/Mustard/Analysis/FilePath SimMACE_mu2eeevv
/Mustard/Analysis/FileMode NEW
/run/beamOn 1000000
/Mustard/Run/PrintRunSummary
