#############################################################################
# Initialization settings
#############################################################################

/control/verbose 0
/run/verbose 0

#/Mustard/Detector/Description/Ixport SimMACE_geom.yaml

/run/initialize

/gps/particle             mu+
/gps/direction            0 0 1        # 0 deg
/gps/pos/centre           0 0 -1 m     # 0 deg
/gps/pos/type             Beam
/gps/pos/shape            Circle
/gps/pos/radius           0 mm
/gps/pos/sigma_r          5 mm
/gps/ene/type             Gauss
/gps/ene/mono             3.224 MeV    # momentum 26.3 MeV
/gps/ene/sigma            0.459 MeV    # momentum spreading 1.9 MeV
/GPSX/NVertex             2000    # 50 kHz beam
/GPSX/PulseWidth          1.5 us

/Mustard/Physics/MuoniumPhysics/Formation/ConversionProbability    0

/MACE/Physics/ApplyProductionCutNearTarget                         no

/MACE/Analysis/SavePrimaryVertexData  no
/MACE/Analysis/SaveDecayVertexData    no
/MACE/Analysis/CoincidenceWithMMS     no
/MACE/Analysis/CoincidenceWithMCP     no
/MACE/Analysis/CoincidenceWithECAL    no
/MACE/Analysis/SaveTTCHitData         no
/MACE/Analysis/SaveCDCHitData         no

#############################################################################
# Run
#############################################################################

/Mustard/Analysis/FilePath SimMACE_beam_mup.root
/Mustard/Analysis/FileMode NEW
/run/beamOn 100
/Mustard/Run/PrintRunSummary
