#############################################################################
# Initialization settings
#############################################################################

/control/verbose 2
#/control/saveHistory
/run/verbose 2

#/Mustard/Detector/Description/Ixport SimMACE_geom.yaml

/run/initialize

/gps/particle             mu+
/gps/direction            0 0 1        # 0 deg
/gps/pos/centre           0 0 -1 m     # 0 deg
/gps/pos/type             Beam
/gps/pos/shape            Circle
/gps/pos/radius           0 mm
/gps/pos/sigma_r          5 mm
/gps/ene/type             Gauss
/gps/ene/mono             3.224 MeV    # momentum 26.3 MeV
/gps/ene/sigma            0.459 MeV    # momentum spreading 1.9 MeV
/GPSX/NVertex             1
/GPSX/PulseWidth          1.5 us

/Mustard/Physics/MuoniumPhysics/Formation/ConversionProbability    0.5

/MACE/Analysis/CoincidenceWithMMS     no
/MACE/Analysis/CoincidenceWithMCP     no
/MACE/Analysis/CoincidenceWithECAL    no

/Mustard/Analysis/FilePath SimMACE_vis
/Mustard/Analysis/FileMode RECREATE

#############################################################################
# Visualization settings
#############################################################################

/vis/open OGL

/vis/viewer/set/autoRefresh no
/vis/verbose errors

/vis/drawVolume

/vis/viewer/set/viewpointVector -1 0.5 0.5
/vis/viewer/set/lightsVector -1 1 1
#/vis/viewer/set/rotationStyle freeRotation
/vis/viewer/set/projection p
/vis/viewer/set/style s
/vis/viewer/set/auxiliaryEdge no
#/vis/viewer/set/lineSegmentsPerCircle 100
/vis/viewer/zoom 2.5

# Visibility
/vis/geometry/set/visibility CDCCell             -1 no
/vis/geometry/set/visibility CDCSuperLayer        0 no
/vis/geometry/set/visibility ECALField            0 no
/vis/geometry/set/visibility ECALMPPCCoupler      0 no
/vis/geometry/set/visibility ECALPMCathode        0 no
/vis/geometry/set/visibility ECALPMTCoupler       0 no
/vis/geometry/set/visibility ECALPMTVacuum        0 no
/vis/geometry/set/visibility MMSField             0 no
/vis/geometry/set/visibility SolenoidFieldS1      0 no
/vis/geometry/set/visibility SolenoidFieldS2      0 no
/vis/geometry/set/visibility SolenoidFieldS3      0 no
/vis/geometry/set/visibility SolenoidFieldT1      0 no
/vis/geometry/set/visibility SolenoidFieldT2      0 no
/vis/geometry/set/visibility TTCVirtualBox       -1 no
/vis/geometry/set/visibility TTCScintillator      0 yes

# Colors
/vis/geometry/set/colour Accelerator                   0     1     1     1     0.1
/vis/geometry/set/colour AcceleratorField              0     1     1     1     0.05
/vis/geometry/set/colour BeamDegrader                  0     1     1     1     0.1
/vis/geometry/set/colour BeamMonitor                   0     1     1     1     0.1
/vis/geometry/set/colour CDCBody                       0     1     1     1     0.01
/vis/geometry/set/colour CDCCell                       0     1     1     1     0.005
/vis/geometry/set/colour CDCFieldWire                  0     1     1     1     0.01
/vis/geometry/set/colour CDCGas                        0     1     1     1     0.005
/vis/geometry/set/colour CDCSenseLayer                 0     1     1     1     0.015
/vis/geometry/set/colour CDCSenseWire                  0     1     1     1     0.01
/vis/geometry/set/colour CDCSensitiveVolume            0     1     1     1     0.005
/vis/geometry/set/colour CDCSuperLayer                 0     1     1     1     0.005
/vis/geometry/set/colour Collimator                    0     1     1     1     0.01
/vis/geometry/set/colour ECALCrystal                   0     1     1     1     0.1
/vis/geometry/set/colour ECALField                     0     1     1     1     0.05
/vis/geometry/set/colour ECALMagnet                    0     1     1     1     0.05
/vis/geometry/set/colour ECALMPPCCoupler               0     1     1     1     0.1
/vis/geometry/set/colour ECALMPPCWindow                0     1     1     1     0.2
/vis/geometry/set/colour ECALPMCathode                 0     1     1     1     0.3
/vis/geometry/set/colour ECALPMTCoupler                0     1     1     1     0.1
/vis/geometry/set/colour ECALPMTShell                  0     1     1     1     0.05
/vis/geometry/set/colour ECALShield                    0     1     1     1     0.05
/vis/geometry/set/colour ECALPMTVacuum                 0     1     1     1     0.01
/vis/geometry/set/colour MCP                           0     1     1     1     0.1
/vis/geometry/set/colour MCPAnode                      0     1     1     1     0.1
/vis/geometry/set/colour MCPChamber                    0     1     1     1     0.05
/vis/geometry/set/colour MCPChamberPipe                0     1     1     1     0.05
/vis/geometry/set/colour MCPChamberPipeVacuum          0     1     1     1     0.05
/vis/geometry/set/colour MCPChamberVacuum              0     1     1     1     0.05
/vis/geometry/set/colour MMSBeamPipe                   0     1     1     1     0.05
/vis/geometry/set/colour MMSBeamPipeVacuum             0     1     1     1     0.01
/vis/geometry/set/colour MMSField                      0     1     1     1     0.05
/vis/geometry/set/colour MMSMagnet                     0     1     1     1     0.05
/vis/geometry/set/colour MMSShield                     0     1     1     1     0.05
/vis/geometry/set/colour ShieldingWall                 0     1     1     1     0.05
/vis/geometry/set/colour SolenoidBeamPipeS1            0     1     1     1     0.1
/vis/geometry/set/colour SolenoidBeamPipeS1Vacuum      0     1     1     1     0.01
/vis/geometry/set/colour SolenoidBeamPipeS2            0     1     1     1     0.1
/vis/geometry/set/colour SolenoidBeamPipeS2Vacuum      0     1     1     1     0.01
/vis/geometry/set/colour SolenoidBeamPipeS3            0     1     1     1     0.1
/vis/geometry/set/colour SolenoidBeamPipeS3Vacuum      0     1     1     1     0.01
/vis/geometry/set/colour SolenoidBeamPipeT1            0     1     1     1     0.1
/vis/geometry/set/colour SolenoidBeamPipeT1Vacuum      0     1     1     1     0.01
/vis/geometry/set/colour SolenoidBeamPipeT2            0     1     1     1     0.1
/vis/geometry/set/colour SolenoidBeamPipeT2Vacuum      0     1     1     1     0.01
/vis/geometry/set/colour SolenoidFieldS1               0     1     1     1     0.05
/vis/geometry/set/colour SolenoidFieldS2               0     1     1     1     0.05
/vis/geometry/set/colour SolenoidFieldS3               0     1     1     1     0.05
/vis/geometry/set/colour SolenoidFieldT1               0     1     1     1     0.05
/vis/geometry/set/colour SolenoidFieldT2               0     1     1     1     0.05
/vis/geometry/set/colour SolenoidS1                    0     1     1     1     0.05
/vis/geometry/set/colour SolenoidS2                    0     1     1     1     0.05
/vis/geometry/set/colour SolenoidS3                    0     1     1     1     0.05
/vis/geometry/set/colour SolenoidShieldS1              0     1     1     1     0.1
/vis/geometry/set/colour SolenoidShieldS2              0     1     1     1     0.1
/vis/geometry/set/colour SolenoidShieldS3              0     1     1     1     0.1
/vis/geometry/set/colour SolenoidShieldT1              0     1     1     1     0.1
/vis/geometry/set/colour SolenoidShieldT2              0     1     1     1     0.1
/vis/geometry/set/colour SolenoidT1                    0     1     1     1     0.05
/vis/geometry/set/colour SolenoidT2                    0     1     1     1     0.05
/vis/geometry/set/colour Target                        0     1     1     1     0.1
/vis/geometry/set/colour TTCLightCoupler               0     1     1     1     0.05
/vis/geometry/set/colour TTCPCB                        0     1     1     1     0.05
/vis/geometry/set/colour TTCScintillator               0     1     1     1     0.05
/vis/geometry/set/colour TTCSilicone                   0     1     1     1     0.05
/vis/geometry/set/colour TTCVirtualBox                 0     1     1     1     0.05
/vis/geometry/set/colour TTCWindow                     0     1     1     1     0.05
/vis/geometry/set/colour World                         0     1     1     1     0.001

/vis/scene/add/date
/vis/scene/add/axes 0 0 0 10 cm
/vis/scene/add/trajectories smooth #rich
/vis/scene/add/hits

/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add mu+
/vis/filtering/trajectories/particleFilter-0/add mu-
/vis/filtering/trajectories/particleFilter-0/add muonium
/vis/filtering/trajectories/particleFilter-0/add anti_muonium
/vis/filtering/trajectories/particleFilter-0/add e+
/vis/filtering/trajectories/particleFilter-0/add e-
/vis/filtering/trajectories/particleFilter-0/add gamma
/vis/filtering/trajectories/particleFilter-0/add opticalphoton
/vis/filtering/trajectories/particleFilter-0/add neutron
/vis/filtering/trajectories/particleFilter-0/add anti_neutron
/vis/filtering/trajectories/particleFilter-0/add proton
/vis/filtering/trajectories/particleFilter-0/add anti_proton
/vis/filtering/trajectories/particleFilter-0/add pi+
/vis/filtering/trajectories/particleFilter-0/add pi-
/vis/filtering/trajectories/particleFilter-0/add pi0

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawAuxPts no
/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsSize 2
/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsSizeType screen
/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsType dots
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawLine yes
/vis/modeling/trajectories/drawByParticleID-0/default/setLineWidth 2
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts yes
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSize 2
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSizeType screen
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsType dots

/vis/modeling/trajectories/drawByParticleID-0/setRGBA muonium 1 0 1 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA anti_muonium 1 0 1 1

/vis/scene/endOfEventAction accumulate

/vis/verbose warnings
/vis/viewer/set/autoRefresh yes
