#############################################################################
# Initialization settings
#############################################################################

/control/verbose 2
#/control/saveHistory
/run/verbose 2

#/Mustard/Detector/Description/Ixport SimMACE_geom.yaml

/run/initialize

/gps/particle             mu+
/gps/direction            0 0 1        # 0 deg
/gps/pos/centre           0 0 -1 m     # 0 deg
/gps/pos/type             Beam
/gps/pos/shape            Circle
/gps/pos/radius           0 mm
/gps/pos/sigma_r          5 mm
/gps/ene/type             Gauss
/gps/ene/mono             3.224 MeV    # momentum 26.3 MeV
/gps/ene/sigma            0.459 MeV    # momentum spreading 1.9 MeV
/GPSX/NVertex             1
/GPSX/PulseWidth          1.5 us

/Mustard/Physics/MuoniumPhysics/Formation/ConversionProbability    0.5

/MACE/Analysis/CoincidenceWithMMS     no
/MACE/Analysis/CoincidenceWithMCP     no
/MACE/Analysis/CoincidenceWithECAL    no

/Mustard/Analysis/FilePath SimMACE_vis.root
/Mustard/Analysis/FileMode RECREATE

#############################################################################
# Visualization settings
#############################################################################

/vis/open OGL

/vis/viewer/set/autoRefresh no
/vis/verbose errors

/vis/drawVolume

/vis/viewer/set/viewpointVector -1 0.5 0.5
/vis/viewer/set/lightsVector -1 1 1
#/vis/viewer/set/rotationStyle freeRotation
/vis/viewer/set/projection p
/vis/viewer/set/style s
/vis/viewer/set/auxiliaryEdge no
#/vis/viewer/set/lineSegmentsPerCircle 100
/vis/viewer/zoom 2.5

# Visibility
/vis/geometry/set/visibility CDCCell             -1 no
/vis/geometry/set/visibility CDCSuperLayer        0 no
/vis/geometry/set/visibility ECALField             0 no
/vis/geometry/set/visibility ECALPMCathode        0 no
/vis/geometry/set/visibility ECALPMTCoupler        0 no
/vis/geometry/set/visibility MMSField             -1 no
/vis/geometry/set/visibility SolenoidFieldS1      0 no
/vis/geometry/set/visibility SolenoidFieldS2      0 no
/vis/geometry/set/visibility SolenoidFieldS3      0 no
/vis/geometry/set/visibility SolenoidFieldT1      0 no
/vis/geometry/set/visibility SolenoidFieldT2      0 no
#/vis/geometry/set/visibility cap2ModuleBox        0 no
#/vis/geometry/set/visibility cap1ModuleBox        0 no
#/vis/geometry/set/visibility topModuleBox         0 no
#/vis/geometry/set/visibility sideModuleBox        0 no


# Colors
/vis/geometry/set/colour FiberHole                       0     1     1     1       0.
/vis/geometry/set/colour Fiber                           0     1     1     1       0.4
/vis/geometry/set/colour SiPMCoupler                     0     1     1     1       0.4
/vis/geometry/set/colour SiPM                            0     1     1     1       0.3
/vis/geometry/set/colour SiPMCathode                     0     1     1     1       0.6




/vis/geometry/set/colour cap2ModuleBox                   0     0.7     0     0.3     0.1
/vis/geometry/set/colour cap1ModuleBox                   0     0     1     0       0.1
/vis/geometry/set/colour topModuleBox                    0     1     0     0       0.1
/vis/geometry/set/colour sideModuleBox                   0     0     0     1       0.

/vis/geometry/set/colour Cap2StripBox                   0     0.7     0     0.3     0.1
/vis/geometry/set/colour Cap1StripBox                   0     0     1     0       0.1
/vis/geometry/set/colour TopStripBox                    0     1     0     0       0.1
/vis/geometry/set/colour SideStripBox                   0     0     0     1       0.1

/vis/geometry/set/colour Cap2Strip                      0     0.7     0     0.3     0.2
/vis/geometry/set/colour Cap1Strip                      0     0     1     0       0.2
/vis/geometry/set/colour TopStrip                       0     1     0     0       0.2
/vis/geometry/set/colour SideStrip                      0     0     0     1       0.2


/vis/geometry/set/visibility Accelerator                   0          no
/vis/geometry/set/visibility AcceleratorField              0          no
/vis/geometry/set/visibility BeamDegrader                  0          no
/vis/geometry/set/visibility BeamMonitor                   0          no
/vis/geometry/set/visibility CDCBody                       0          no
/vis/geometry/set/visibility CDCCell                       0          no
/vis/geometry/set/visibility CDCFieldWire                  0          no
/vis/geometry/set/visibility CDCGas                        0          no
/vis/geometry/set/visibility CDCSenseLayer                 0          no
/vis/geometry/set/visibility CDCSenseWire                  0          no
/vis/geometry/set/visibility CDCSensitiveVolume            0          no
/vis/geometry/set/visibility CDCSuperLayer                 0          no
/vis/geometry/set/visibility Collimator                    0          no
/vis/geometry/set/visibility ECALCrystal                   0          no
/vis/geometry/set/visibility ECALField                     0          no
/vis/geometry/set/visibility ECALMagnet                    0          no
#/vis/geometry/set/visibility ECALShield                    0          no

/vis/geometry/set/visibility ECALPMTCoupler                0     no
/vis/geometry/set/visibility ECALPMTShell                  0     no
/vis/geometry/set/visibility ECALPMTVacuum                 0     no
/vis/geometry/set/visibility ECALMPPCWindow                0     no
/vis/geometry/set/visibility ECALMPPCCoupler               0     no
/vis/geometry/set/visibility ECALPMCathode                 0     no

/vis/geometry/set/visibility MCP                           0     no
/vis/geometry/set/visibility MCPAnode                      0     no
/vis/geometry/set/visibility MCPChamber                    0     no
/vis/geometry/set/visibility MCPChamberPipe                0     no
/vis/geometry/set/visibility MCPChamberPipeVacuum          0     no
/vis/geometry/set/visibility MCPChamberVacuum              0     no
/vis/geometry/set/visibility MMSBeamPipe                   0     no
/vis/geometry/set/visibility MMSBeamPipeVacuum             0     no
/vis/geometry/set/visibility MMSField                      0     no
/vis/geometry/set/visibility MMSMagnet                     0     no
/vis/geometry/set/visibility MMSShield                     0     no
/vis/geometry/set/visibility ShieldingWall                 0     no
/vis/geometry/set/visibility SolenoidBeamPipeS1            0     no
/vis/geometry/set/visibility SolenoidBeamPipeS1Vacuum      0     no
/vis/geometry/set/visibility SolenoidBeamPipeS2            0     no
/vis/geometry/set/visibility SolenoidBeamPipeS2Vacuum      0     no
/vis/geometry/set/visibility SolenoidBeamPipeS3            0     no
/vis/geometry/set/visibility SolenoidBeamPipeS3Vacuum      0     no
/vis/geometry/set/visibility SolenoidBeamPipeT1            0     no
/vis/geometry/set/visibility SolenoidBeamPipeT1Vacuum      0     no
/vis/geometry/set/visibility SolenoidBeamPipeT2            0     no
/vis/geometry/set/visibility SolenoidBeamPipeT2Vacuum      0     no
/vis/geometry/set/visibility SolenoidFieldS1               0     no
/vis/geometry/set/visibility SolenoidFieldS2               0     no
/vis/geometry/set/visibility SolenoidFieldS3               0     no
/vis/geometry/set/visibility SolenoidFieldT1               0     no
/vis/geometry/set/visibility SolenoidFieldT2               0     no
/vis/geometry/set/visibility SolenoidS1                    0     no
/vis/geometry/set/visibility SolenoidS2                    0     no
/vis/geometry/set/visibility SolenoidS3                    0     no
/vis/geometry/set/visibility SolenoidShieldS1              0     no
/vis/geometry/set/visibility SolenoidShieldS2              0     no
/vis/geometry/set/visibility SolenoidShieldS3              0     no
/vis/geometry/set/visibility SolenoidShieldT1              0     no
/vis/geometry/set/visibility SolenoidShieldT2              0     no
/vis/geometry/set/visibility SolenoidT1                    0     no
/vis/geometry/set/visibility SolenoidT2                    0     no
/vis/geometry/set/visibility Target                        0     no
/vis/geometry/set/visibility TTC                           0     no
/vis/geometry/set/visibility World                         0     no

/vis/scene/add/date
/vis/scene/add/axes 0 0 0 10 cm
/vis/scene/add/trajectories smooth #rich
/vis/scene/add/hits

/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add mu+
/vis/filtering/trajectories/particleFilter-0/add mu-
/vis/filtering/trajectories/particleFilter-0/add muonium
/vis/filtering/trajectories/particleFilter-0/add anti_muonium
/vis/filtering/trajectories/particleFilter-0/add e+
/vis/filtering/trajectories/particleFilter-0/add e-
/vis/filtering/trajectories/particleFilter-0/add gamma
/vis/filtering/trajectories/particleFilter-0/add opticalphoton
/vis/filtering/trajectories/particleFilter-0/add neutron
/vis/filtering/trajectories/particleFilter-0/add anti_neutron
/vis/filtering/trajectories/particleFilter-0/add proton
/vis/filtering/trajectories/particleFilter-0/add anti_proton
/vis/filtering/trajectories/particleFilter-0/add pi+
/vis/filtering/trajectories/particleFilter-0/add pi-
/vis/filtering/trajectories/particleFilter-0/add pi0

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawAuxPts no
/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsSize 2
/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsSizeType screen
/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsType dots
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawLine yes
/vis/modeling/trajectories/drawByParticleID-0/default/setLineWidth 2
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts yes
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSize 2
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSizeType screen
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsType dots

/vis/modeling/trajectories/drawByParticleID-0/setRGBA muonium 1 0 1 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA anti_muonium 1 0 1 1

/vis/scene/endOfEventAction accumulate

/vis/verbose warnings
/vis/viewer/set/autoRefresh yes
