/control/verbose 0
/run/verbose 0

#/MACE/Physics/UseRadioactiveDecayPhysics
#/MACE/Physics/UseOpticalPhysics
#/process/optical/scintillation/setFiniteRiseTime true

#/Mustard/Detector/Description/Import SimMACEPhaseI_geom.yaml

/run/initialize

/MACE/Generator/SwitchToGPSX

/gps/particle gamma
/gps/ene/mono 53.085 MeV
/gps/pos/centre 0. 0. 0. cm
/gps/ang/type iso

/MACE/Analysis/CoincidenceWithMRPC    no
/MACE/Analysis/CoincidenceWithECAL    no

/Mustard/Analysis/FilePath SimMACEPhaseI_gamma
/Mustard/Analysis/FileMode RECREATE

/run/beamOn 1000000
/Mustard/Run/PrintRunSummary
