#############################################################################
# Initialization settings
#############################################################################

/control/verbose 2
/control/saveHistory
/run/verbose 2

#/MACE/Physics/UseRadioactiveDecayPhysics
#/MACE/Physics/UseOpticalPhysics

/Mustard/Detector/Description/Import SimMACEPhaseI_geom.yaml

/run/initialize

/MACE/Generator/SwitchToGPSX
/gps/particle             mu+
/gps/direction            0 0 1        # 0 deg
/gps/pos/centre           0 0 -50 cm   # 0 deg
/gps/pos/type             Beam
/gps/pos/shape            Circle
/gps/pos/radius           0 mm
/gps/pos/sigma_r          5 mm
/gps/ene/type             Gauss
/gps/ene/mono             3.224 MeV    # momentum 26.3 MeV
/gps/ene/sigma            0.459 MeV    # momentum spreading 1.9 MeV
/GPSX/NVertex             1
/GPSX/PulseWidth          0 ns

/Mustard/Physics/MuonDecay/RadiativeDecay/BR 0
/Mustard/Physics/MuonDecay/ICDecay/BR 0
/Mustard/Physics/MuonDecay/DoubleRadiativeDecay/BR 1
/Mustard/Physics/MuonDecay/UpdateDecayBR
/Mustard/Physics/MuoniumDecay/DoubleRadiativeDecay/BR 0
/Mustard/Physics/MuoniumDecay/ElectronPairDecay/BR 0
/Mustard/Physics/MuoniumDecay/UpdateDecayBR

/MACE/Analysis/CoincidenceWithMRPC    no
/MACE/Analysis/CoincidenceWithECAL    no

/MACE/Analysis/FilePath SimMACEPhaseI_vis.root
/MACE/Analysis/FileMode RECREATE

#############################################################################
# Visualization settings
#############################################################################

/vis/open OGL

/vis/viewer/set/autoRefresh no
/vis/verbose errors

/vis/drawVolume

/vis/viewer/set/viewpointVector -1 0.5 -1
/vis/viewer/set/lightsVector -1 1 1
#/vis/viewer/set/rotationStyle freeRotation
/vis/viewer/set/projection p
/vis/viewer/set/style s
/vis/viewer/set/auxiliaryEdge no
#/vis/viewer/set/lineSegmentsPerCircle 100
/vis/viewer/zoom 1.5
#/vis/viewer/addCutawayPlane 0 0 0 m 1 0 0

# Visibility
/vis/geometry/set/visibility CentralBeamPipeVacuum      0 no
/vis/geometry/set/visibility World                      0 no
/vis/geometry/set/visibility ECALPMCathode              0 no
/vis/geometry/set/visibility ECALPMTCoupler             0 no
/vis/geometry/set/visibility MRPCGas                    0 no

# Colors
/vis/geometry/set/colour CentralBeamPipe                        0     1     1     1     0.1
        
/vis/geometry/set/colour MRPCGasTank                            0     1     1     1     0.05
/vis/geometry/set/colour MRPCInnerGlass                         0     1     1     1     0.1
/vis/geometry/set/colour MRPCOuterGlass                         0     1     1     1     0.1
/vis/geometry/set/colour MRPCAnode                              0     1     1     1     0.1
/vis/geometry/set/colour MRPCMylar                              0     1     1     1     0.1
/vis/geometry/set/colour MRPCPCB                                0     1     1     1     0.1
/vis/geometry/set/colour MRPCHoneyComb                          0     1     1     1     0.1
        
/vis/geometry/set/colour ECALCrystal                            0     1     1     1     0.1
/vis/geometry/set/colour ECALPMTCoupler                         0     1     1     1     0.1
/vis/geometry/set/colour ECALPMTShell                           0     1     1     1     0.05
/vis/geometry/set/colour ECALPMTVacuum                          0     1     1     1     0.
/vis/geometry/set/colour ECALMPPCWindow                         0     1     1     1     0.2
/vis/geometry/set/colour ECALMPPCCoupler                        0     1     1     1     0.1
/vis/geometry/set/colour ECALPMCathode                          0     1     1     1     0.3
        
/vis/geometry/set/colour SciFiTrackerHelicalFiber               0     1     1     1     0.1
/vis/geometry/set/colour SciFiTrackerHelicalFiberCore           0     1     1     1     0.05
/vis/geometry/set/colour SciFiTrackerTransverseFiber            0     1     1     1     0.1
/vis/geometry/set/colour SciFiTrackerTransverseFiberCore        0     1     1     1     0.05
/vis/geometry/set/colour SciFiTrackerHelicalLightGuide          0     1     1     1     0.1
/vis/geometry/set/colour SciFiTrackerHelicalLightGuideCore      0     1     1     1     0.05
/vis/geometry/set/colour SciFiTrackerTransverseLightGuide       0     1     1     1     0.1
/vis/geometry/set/colour SciFiTrackerTransverseLightGuideCore   0     1     1     1     0.05
/vis/geometry/set/colour SciFiTrackerBraket                     0     1     1     1     0.05


/vis/geometry/set/colour Target                             0     1     1     1     0.1

/vis/scene/add/date
/vis/scene/add/axes 0 0 0 10 cm
/vis/scene/add/trajectories smooth #rich
/vis/scene/add/hits

/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add mu+
/vis/filtering/trajectories/particleFilter-0/add mu-
/vis/filtering/trajectories/particleFilter-0/add muonium
/vis/filtering/trajectories/particleFilter-0/add anti_muonium
/vis/filtering/trajectories/particleFilter-0/add e+
/vis/filtering/trajectories/particleFilter-0/add e-
/vis/filtering/trajectories/particleFilter-0/add gamma
/vis/filtering/trajectories/particleFilter-0/add opticalphoton
/vis/filtering/trajectories/particleFilter-0/add neutron
/vis/filtering/trajectories/particleFilter-0/add anti_neutron
/vis/filtering/trajectories/particleFilter-0/add proton
/vis/filtering/trajectories/particleFilter-0/add anti_proton
/vis/filtering/trajectories/particleFilter-0/add pi+
/vis/filtering/trajectories/particleFilter-0/add pi-
/vis/filtering/trajectories/particleFilter-0/add pi0

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawAuxPts no
/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsSize 2
/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsSizeType screen
/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsType dots
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawLine yes
/vis/modeling/trajectories/drawByParticleID-0/default/setLineWidth 2
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts yes
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSize 2
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSizeType screen
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsType dots

/vis/modeling/trajectories/drawByParticleID-0/setRGBA muonium 1 0 1 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA anti_muonium 1 0 1 1

/vis/scene/endOfEventAction accumulate

/vis/verbose warnings
/vis/viewer/set/autoRefresh yes
