#############################################################################
# Initialization settings
#############################################################################

/control/verbose 0
/run/verbose 0

#/Mustard/Detector/Description/Ixport mms_geom.yaml

/MACE/Physics/UseOpticalPhysics

/run/initialize

/process/optical/scintillation/setFiniteRiseTime true

/MACE/Generator/SwitchToGPSX
/gps/particle                         e-
/gps/pos/type                         Point
/gps/pos/centre                       0 0 0 m
/gps/ang/type                         iso
/gps/ene/type                         Lin
/gps/ene/gradient                     0
/gps/ene/intercept                    1
/gps/ene/min                          1 keV
/gps/ene/max                          52.83 MeV

/MACE/Analysis/SaveTTCHitData         yes
/MACE/Analysis/SaveTTCSiPMHitData     yes
/MACE/Analysis/SaveCDCHitData         yes

#############################################################################
# Run
#############################################################################

/Mustard/Analysis/FilePath SimMMS_em_flat
/Mustard/Analysis/FileMode NEW
/run/beamOn 10000
/Mustard/Run/PrintRunSummary
