#############################################################################
# Initialization settings
#############################################################################

/control/verbose 2
#/control/saveHistory
/run/verbose 2

#/Mustard/Detector/Description/Ixport mms_geom.yaml

/MACE/Physics/UseOpticalPhysics

/run/initialize

/process/optical/scintillation/setFiniteRiseTime true

/MACE/Generator/SwitchToGPSX
/gps/particle                         e+
/gps/pos/type                         Point
/gps/pos/centre                       0 0 0 m
/gps/ang/type                         iso
/gps/ene/mono                         52.8 MeV

/MACE/Analysis/SaveTTCHitData         yes
/MACE/Analysis/SaveTTCSiPMHitData     yes
/MACE/Analysis/SaveCDCHitData         yes


/Mustard/Analysis/FilePath SimMACE_vis
/Mustard/Analysis/FileMode RECREATE

#############################################################################
# Visualization settings
#############################################################################

/vis/open OGL

/vis/viewer/set/autoRefresh no
/vis/verbose errors

/vis/drawVolume

/vis/viewer/set/viewpointVector -1 0.5 0.5
/vis/viewer/set/lightsVector -1 1 1
#/vis/viewer/set/rotationStyle freeRotation
/vis/viewer/set/projection p
/vis/viewer/set/style s
/vis/viewer/set/auxiliaryEdge no
#/vis/viewer/set/lineSegmentsPerCircle 100
/vis/viewer/zoom 2.5

# Visibility
/vis/geometry/set/visibility CDCCell             -1 no
/vis/geometry/set/visibility CDCSuperLayer        0 no
/vis/geometry/set/visibility MMSField             0 no
/vis/geometry/set/visibility TTCVirtualBox       -1 no
/vis/geometry/set/visibility TTCScintillator      0 yes

# Colors
/vis/geometry/set/colour AcceleratorField              0     1     1     1     0.05
/vis/geometry/set/colour BeamDegrader                  0     1     1     1     0.1
/vis/geometry/set/colour BeamMonitor                   0     1     1     1     0.1
/vis/geometry/set/colour CDCBody                       0     1     1     1     0.05
/vis/geometry/set/colour CDCCell                       0     1     1     1     0.005
/vis/geometry/set/colour CDCFieldWire                  0     1     1     1     0.01
/vis/geometry/set/colour CDCGas                        0     1     1     1     0.005
/vis/geometry/set/colour CDCSenseLayer                 0     1     1     1     0.015
/vis/geometry/set/colour CDCSenseWire                  0     1     1     1     0.01
/vis/geometry/set/colour CDCSensitiveVolume            0     1     1     1     0.005
/vis/geometry/set/colour CDCSuperLayer                 0     1     1     1     0.005
/vis/geometry/set/colour MMSBeamPipe                   0     1     1     1     0.05
/vis/geometry/set/colour MMSBeamPipeVacuum             0     1     1     1     0.01
/vis/geometry/set/colour MMSField                      0     1     1     1     0.05
/vis/geometry/set/colour MMSMagnet                     0     1     1     1     0.05
/vis/geometry/set/colour MMSShield                     0     1     1     1     0.05
/vis/geometry/set/colour TTCVirtualBox                 0     1     1     1     0.05
/vis/geometry/set/colour TTCPCB                        0     1     1     1     0.05
/vis/geometry/set/colour TTCWindow                     0     1     1     1     0.05
/vis/geometry/set/colour TTCSilicone                   0     1     1     1     0.05
/vis/geometry/set/colour TTCLightCoupler               0     1     1     1     0.05
/vis/geometry/set/colour TTCScintillator               0     1     1     1     0.05
/vis/geometry/set/colour Target                        0     1     1     1     0.1
/vis/geometry/set/colour World                         0     1     1     1     0.001

/vis/scene/add/date
/vis/scene/add/axes 0 0 0 10 cm
/vis/scene/add/trajectories smooth #rich
/vis/scene/add/hits

/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add mu+
/vis/filtering/trajectories/particleFilter-0/add mu-
/vis/filtering/trajectories/particleFilter-0/add muonium
/vis/filtering/trajectories/particleFilter-0/add anti_muonium
/vis/filtering/trajectories/particleFilter-0/add e+
/vis/filtering/trajectories/particleFilter-0/add e-
/vis/filtering/trajectories/particleFilter-0/add gamma
/vis/filtering/trajectories/particleFilter-0/add opticalphoton
/vis/filtering/trajectories/particleFilter-0/add neutron
/vis/filtering/trajectories/particleFilter-0/add anti_neutron
/vis/filtering/trajectories/particleFilter-0/add proton
/vis/filtering/trajectories/particleFilter-0/add anti_proton
/vis/filtering/trajectories/particleFilter-0/add pi+
/vis/filtering/trajectories/particleFilter-0/add pi-
/vis/filtering/trajectories/particleFilter-0/add pi0

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawAuxPts no
/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsSize 2
/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsSizeType screen
/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsType dots
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawLine yes
/vis/modeling/trajectories/drawByParticleID-0/default/setLineWidth 2
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts yes
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSize 2
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSizeType screen
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsType dots

/vis/modeling/trajectories/drawByParticleID-0/setRGBA muonium 1 0 1 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA anti_muonium 1 0 1 1

/vis/scene/endOfEventAction accumulate

/vis/verbose warnings
/vis/viewer/set/autoRefresh yes
