#pragma once

#include <initializer_list>

namespace MACE::SimTTC {

constexpr auto defaultMacro = {
    "#############################################################################",
    "# Initialization settings",
    "#############################################################################",
    "",
    "/control/verbose 2",
    "#/control/saveHistory",
    "/run/verbose 2",
    "",
    "/Mustard/Detector/Description/Ixport SimTTC.yaml",
    "",
    "/MACE/Physics/UseOpticalPhysics",
    "/run/initialize",
    "/process/optical/scintillation/setFiniteRiseTime true",
    "",
    "/gps/particle                         e+",
    "/gps/pos/type                         Point",
    "/gps/pos/centre                       0 0 0 m",
    "/gps/ang/type                         iso",
    "/gps/ene/mono                         52.8 MeV",
    "",
    "/MACE/Analysis/SaveTTCHitData         yes",
    "/MACE/Analysis/SaveTTCSiPMHitData     yes",
    "",
    "/Mustard/Analysis/FilePath SimTTC_vis.root",
    "/Mustard/Analysis/FileMode RECREATE",
    "",

#if MUSTARD_USE_G4VIS

    "#############################################################################",
    "# Visualization settings",
    "#############################################################################",
    "",
    "/vis/open OGL",
    "",
    "/vis/viewer/set/autoRefresh false",
    "/vis/verbose errors",
    "",
    "/vis/drawVolume",
    "",
    "/vis/viewer/set/viewpointVector -1 0.5 0.5",
    "/vis/viewer/set/lightsVector -1 1 1",
    "#/vis/viewer/set/rotationStyle freeRotation",
    "/vis/viewer/set/projection p",
    "/vis/viewer/set/style s",
    "/vis/viewer/set/auxiliaryEdge false",
    "#/vis/viewer/set/lineSegmentsPerCircle 100",
    "/vis/viewer/zoom 2.5",
    "",
    "# Visibility",
    "/vis/geometry/set/visibility MMSField             0 false",
    "/vis/geometry/set/visibility TTCVirtualBox       -1 no",
    "/vis/geometry/set/visibility TTCScintillator      0 yes",
    "",
    "",
    "# Colors",
    "/vis/geometry/set/colour MMSField                      0     1     1     1     0.05",
    "/vis/geometry/set/colour TTCVirtualBox                 0     1     1     1     0.05",
    "/vis/geometry/set/colour TTCPCB                        0     1     1     1     0.05",
    "/vis/geometry/set/colour TTCWindow                     0     1     1     1     0.05",
    "/vis/geometry/set/colour TTCSilicone                   0     1     1     1     0.05",
    "/vis/geometry/set/colour TTCLightCoupler               0     1     1     1     0.05",
    "/vis/geometry/set/colour TTCScintillator               0     1     1     1     0.05",
    "/vis/geometry/set/colour World                         0     1     1     1     0.001",
    "",
    "/vis/scene/add/date",
    "/vis/scene/add/axes 0 0 0 10 cm",
    "/vis/scene/add/trajectories smooth #rich",
    "/vis/scene/add/hits",
    "",
    "/vis/filtering/trajectories/create/particleFilter",
    "/vis/filtering/trajectories/particleFilter-0/add mu+",
    "/vis/filtering/trajectories/particleFilter-0/add mu-",
    "/vis/filtering/trajectories/particleFilter-0/add muonium",
    "/vis/filtering/trajectories/particleFilter-0/add anti_muonium",
    "/vis/filtering/trajectories/particleFilter-0/add e+",
    "/vis/filtering/trajectories/particleFilter-0/add e-",
    "/vis/filtering/trajectories/particleFilter-0/add gamma",
    "/vis/filtering/trajectories/particleFilter-0/add opticalphoton",
    "/vis/filtering/trajectories/particleFilter-0/add neutron",
    "/vis/filtering/trajectories/particleFilter-0/add anti_neutron",
    "/vis/filtering/trajectories/particleFilter-0/add proton",
    "/vis/filtering/trajectories/particleFilter-0/add anti_proton",
    "/vis/filtering/trajectories/particleFilter-0/add pi+",
    "/vis/filtering/trajectories/particleFilter-0/add pi-",
    "/vis/filtering/trajectories/particleFilter-0/add pi0",
    "",
    "/vis/modeling/trajectories/create/drawByParticleID",
    "/vis/modeling/trajectories/drawByParticleID-0/default/setDrawAuxPts false",
    "/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsSize 2",
    "/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsSizeType screen",
    "/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsType dots",
    "/vis/modeling/trajectories/drawByParticleID-0/default/setDrawLine true",
    "/vis/modeling/trajectories/drawByParticleID-0/default/setLineWidth 2",
    "/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true",
    "/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSize 2",
    "/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSizeType screen",
    "/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsType dots",
    "",
    "/vis/modeling/trajectories/drawByParticleID-0/setRGBA muonium 1 0 1 1",
    "/vis/modeling/trajectories/drawByParticleID-0/setRGBA anti_muonium 1 0 1 1",
    "",
    "/vis/scene/endOfEventAction accumulate",
    "",
    "/vis/verbose warnings",
    "/vis/viewer/set/autoRefresh true",

#endif

    ""};

} // namespace MACE::SimTTC
