/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/MACE/Physics/UseRadioactiveDecayPhysics
#/MACE/Physics/UseOpticalPhysics

/run/initialize

/MACE/Generator/SwitchToGPSX
/gps/particle gamma
/gps/ene/mono 0.511 MeV
/gps/pos/centre 0. 0. 0. cm
/gps/ang/type iso

/Mustard/Analysis/FilePath SimECAL_sig.root
/Mustard/Analysis/FileMode NEW
/run/beamOn 1000
/Mustard/Run/PrintRunSummary
