/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/MACE/Physics/UseRadioactiveDecayPhysics
#/MACE/Physics/UseOpticalPhysics

/run/initialize

/MACE/Generator/SwitchToGPSX
/gps/particle e+
/gps/direction 0 0 1
/gps/ene/mono 5 keV
/gps/pos/type Beam
/gps/pos/radius 0 cm
/gps/pos/sigma_r 5.6 mm
/gps/pos/centre 0 0 -10 cm

/MACE/Analysis/CoincidenceWithMCP     yes

/MACE/Analysis/FilePath SimECAL_sig.root
/MACE/Analysis/FileMode NEW

/run/beamOn 1000
