/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/MACE/Physics/UseRadioactiveDecayPhysics
#/MACE/Physics/UseOpticalPhysics

/run/initialize

/MACE/Generator/SwitchToGPSX

/gps/source/intensity 1
/gps/particle ion
/gps/ion 11 22
/gps/ene/mono 0 MeV
/gps/pos/centre 0 0 0 cm

/gps/source/add 1
/gps/particle ion
/gps/ion 55 137
/gps/ene/mono 0 MeV
/gps/pos/centre 0 0 0 cm

/gps/source/add 1
/gps/particle ion
/gps/ion 63 152
/gps/ene/mono 0 MeV
/gps/pos/centre 0 0 0 cm

/MACE/Analysis/FilePath SimECAL_source.root
/MACE/Analysis/FileMode NEW
/run/beamOn 1000
/Mustard/Run/PrintRunSummary
