/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

#/MACE/Physics/UseRadioactiveDecayPhysics
#/MACE/Physics/UseOpticalPhysics

#/Mustard/Detector/Description/Import test_10L_15R.yaml

/run/initialize

/MACE/Generator/SwitchToGPSX

/gps/particle gamma
/gps/ene/mono 0.511 MeV
/gps/pos/centre 0. 0. 0. cm
/gps/direction -0.231259 0.883817 -0.386541

/MACE/Analysis/FilePath test.root
/MACE/Analysis/FileMode RECREATE
/run/beamOn 10000

/Mustard/Run/PrintRunSummary
