#############################################################################
# Initialization settings
#############################################################################

/control/verbose 2
/control/saveHistory
/run/verbose 2

/MACE/Physics/UseRadioactiveDecayPhysics
#/MACE/Physics/UseOpticalPhysics

#/Mustard/Detector/Description/Import SimECAL.yaml

/run/initialize

/MACE/Generator/SwitchToGPSX

/MACE/Analysis/FilePath SimECAL_vis.root
/MACE/Analysis/FileMode RECREATE

#############################################################################
# Visualization settings
#############################################################################

/vis/open OGL

/vis/viewer/set/autoRefresh no
/vis/verbose errors

/vis/drawVolume

/vis/viewer/set/viewpointVector -1 0.5 0.5
/vis/viewer/set/lightsVector -1 1 1
#/vis/viewer/set/rotationStyle freeRotation
/vis/viewer/set/projection p
/vis/viewer/set/style s
/vis/viewer/set/auxiliaryEdge no
#/vis/viewer/set/lineSegmentsPerCircle 100
/vis/viewer/zoom 1.5
#/vis/viewer/addCutawayPlane 0 0 0

# Visibility
/vis/geometry/set/visibility ECALField             0 no
/vis/geometry/set/visibility ECALPMCathode         0 no
/vis/geometry/set/visibility ECALPMTCoupler        0 no

# Colors
/vis/geometry/set/colour ECALCrystal                   0     1     1     1     0.1
/vis/geometry/set/colour ECALField                     0     1     1     1     0.05
/vis/geometry/set/colour ECALMagnet                    0     1     1     1     0.05
/vis/geometry/set/colour ECALShield                    0     1     1     1     0.05
/vis/geometry/set/colour ECALPMCathode                 0     1     1     1     0.3
/vis/geometry/set/colour ECALPMTCoupler                0     1     1     1     0.1
/vis/geometry/set/colour ECALPMTShell                  0     1     1     1     0.05
/vis/geometry/set/colour ECALPMTVacuum                 0     1     1     1     0.
/vis/geometry/set/colour ECALMPPCWindow                0     1     1     1     0.2
/vis/geometry/set/colour ECALMPPCCoupler               0     1     1     1     0.1

/vis/scene/add/date
/vis/scene/add/axes 0 0 0 10 cm
/vis/scene/add/trajectories smooth #rich
/vis/scene/add/hits

/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add mu+
/vis/filtering/trajectories/particleFilter-0/add mu-
/vis/filtering/trajectories/particleFilter-0/add muonium
/vis/filtering/trajectories/particleFilter-0/add anti_muonium
/vis/filtering/trajectories/particleFilter-0/add e+
/vis/filtering/trajectories/particleFilter-0/add e-
/vis/filtering/trajectories/particleFilter-0/add gamma
/vis/filtering/trajectories/particleFilter-0/add opticalphoton
/vis/filtering/trajectories/particleFilter-0/add neutron
/vis/filtering/trajectories/particleFilter-0/add anti_neutron
/vis/filtering/trajectories/particleFilter-0/add proton
/vis/filtering/trajectories/particleFilter-0/add anti_proton
/vis/filtering/trajectories/particleFilter-0/add pi+
/vis/filtering/trajectories/particleFilter-0/add pi-
/vis/filtering/trajectories/particleFilter-0/add pi0

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawAuxPts no
/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsSize 2
/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsSizeType screen
/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsType dots
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawLine yes
/vis/modeling/trajectories/drawByParticleID-0/default/setLineWidth 2
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts yes
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSize 2
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSizeType screen
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsType dots

/vis/modeling/trajectories/drawByParticleID-0/setRGBA muonium 1 0 1 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA anti_muonium 1 0 1 1

/vis/scene/endOfEventAction accumulate

/vis/verbose warnings
/vis/viewer/set/autoRefresh yes
/vis/geometry/set/visibility World 0 no

#############################################################################
# General Particle Source settings
#############################################################################

/gps/particle gamma
/gps/ene/mono 0.511 MeV
/gps/pos/centre 0. 0. 0. cm
/gps/direction -0.231259 0.883817 -0.386541
