#############################################################################
#
# Macro file demo for SimTarget in interactive session
#
#############################################################################

#############################################################################
# Initialization settings
#############################################################################

# Set some default verbose
/control/verbose 2
/control/saveHistory
/run/verbose 2

# I/O & Analysis
/MACE/Analysis/FilePath                        SimTarget_vis.root
/MACE/Analysis/FileMode                        RECREATE
/MACE/Analysis/EnableYieldAnalysis             yes

# Geometry
#/Mustard/Detector/Description/Import              geom.yaml

# Initialize kernel
/run/initialize

# Muon beam properties
/gps/particle             mu+
/gps/direction            0 0 1
/gps/pos/centre           0 0 -10 cm
/gps/pos/type             Beam
/gps/pos/shape            Circle
/gps/pos/radius           20 mm
/gps/ene/type             Gauss
# CiADS full-solenoid focusing beam, 0.5-mA-proton beam on C target
/gps/ene/mono             3.346 MeV    # momentum 26.8 MeV
/gps/ene/sigma            0.393 MeV    # momentum spreading 1.6 MeV
## CiADS solenoid + QM focusing beam, 0.5-mA-proton beam on C target
#/gps/ene/mono             3.248 MeV    # momentum 26.4 MeV
#/gps/ene/sigma            0.339 MeV    # momentum spreading 1.4 MeV

# Set physics
/Mustard/Physics/MuoniumPhysics/Formation/ConversionProbability    0

# kill secondaries
/MACE/Action/KillIrrelevance    yes

#############################################################################
# Visualization settings
#############################################################################

/vis/open OGL

/vis/viewer/set/autoRefresh no
/vis/verbose errors

/vis/drawVolume

/vis/viewer/set/viewpointVector -1 0.5 0.5
#/vis/viewer/set/lightsVector -1 1 1
#/vis/viewer/set/rotationStyle freeRotation
/vis/viewer/set/projection p
/vis/viewer/set/style s
/vis/viewer/set/auxiliaryEdge no
/vis/viewer/set/lineSegmentsPerCircle 100
/vis/viewer/zoom 1

# Colors
/vis/geometry/set/colour BeamMonitor     0     1     1     1     0.5
/vis/geometry/set/colour BeamDegrader    0     1     1     1     0.5
/vis/geometry/set/colour Target          0     1     1     1     0.5
/vis/geometry/set/colour World           0     1     1     1     0.01

/vis/scene/add/date
/vis/scene/add/axes 0 0 0 1 cm
/vis/scene/add/trajectories smooth #rich
/vis/scene/add/hits

/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add e+
#/vis/filtering/trajectories/particleFilter-0/add e-
#/vis/filtering/trajectories/particleFilter-0/add gamma
/vis/filtering/trajectories/particleFilter-0/add muonium
/vis/filtering/trajectories/particleFilter-0/add anti_muonium
/vis/filtering/trajectories/particleFilter-0/add mu+

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawAuxPts no
/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsSize 2
/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsSizeType screen
/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsType dots
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawLine yes
/vis/modeling/trajectories/drawByParticleID-0/default/setLineWidth 2
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts yes
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSize 2
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSizeType screen
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsType dots

/vis/modeling/trajectories/drawByParticleID-0/setRGBA muonium 1 0 1 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA anti_muonium 1 0 1 1

/vis/scene/endOfEventAction accumulate

/vis/verbose warnings
/vis/viewer/set/autoRefresh yes
