// -*- C++ -*-
//
// Copyright (C) 2020-2025  MACESW developers
//
// This file is part of MACESW, Muonium-to-Antimuonium Conversion Experiment
// offline software.
//
// MACESW is free software: you can redistribute it and/or modify it under the
// terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version.
//
// MACESW is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
// A PARTICULAR PURPOSE. See the GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along with
// MACESW. If not, see <https://www.gnu.org/licenses/>.

#pragma once

#include <initializer_list>

namespace MACE::SimDose {

constexpr auto defaultMacro = {
    "#############################################################################",
    "# Initialization settings",
    "#############################################################################",
    "",
    "/control/verbose 2",
    "#/control/saveHistory",
    "/run/verbose 2",
    "",
    "#/Mustard/Detector/Description/Ixport SimDose_geom.yaml",
    "",
    "/run/initialize",
    "",
    "/gps/particle             mu+",
    "/gps/direction            0 0 1        # 0 deg",
    "/gps/pos/centre           0 0 -1 m     # 0 deg",
    "/gps/pos/type             Beam",
    "/gps/pos/shape            Circle",
    "/gps/pos/radius           0 mm",
    "/gps/pos/sigma_r          5 mm",
    "/gps/ene/type             Gauss",
    "/gps/ene/mono             3.647 MeV   # momentum 28 MeV",
    "/gps/ene/sigma            0.1793 MeV  # momentum spreading 2.5%",
    "/GPSX/NVertex             1",
    "/GPSX/PulseWidth          0 ns",
    "",
    "/MACE/Analysis/AddMap World",
    "/MACE/Analysis/MapNBinX 300",
    "/MACE/Analysis/MapXMin -3 m",
    "/MACE/Analysis/MapXMax 3 m",
    "/MACE/Analysis/MapNBinY 100",
    "/MACE/Analysis/MapYMin -1 m",
    "/MACE/Analysis/MapYMax 1 m",
    "/MACE/Analysis/MapNBinZ 400",
    "/MACE/Analysis/MapZMin -4 m",
    "/MACE/Analysis/MapZMax 4 m",
    "",
    "/MACE/Analysis/AddMap Target",
    "/MACE/Analysis/MapNBinX 200",
    "/MACE/Analysis/MapXMin -100 mm",
    "/MACE/Analysis/MapXMax 100 mm",
    "/MACE/Analysis/MapNBinY 200",
    "/MACE/Analysis/MapYMin -100 mm",
    "/MACE/Analysis/MapYMax 100 mm",
    "/MACE/Analysis/MapNBinZ 200",
    "/MACE/Analysis/MapZMin -100 mm",
    "/MACE/Analysis/MapZMax 100 mm",
    "",
    "/MACE/Analysis/AddMap CDC",
    "/MACE/Analysis/MapNBinX 200",
    "/MACE/Analysis/MapXMin -500 mm",
    "/MACE/Analysis/MapXMax 500 mm",
    "/MACE/Analysis/MapNBinY 200",
    "/MACE/Analysis/MapYMin -500 mm",
    "/MACE/Analysis/MapYMax 500 mm",
    "/MACE/Analysis/MapNBinZ 360",
    "/MACE/Analysis/MapZMin -900 mm",
    "/MACE/Analysis/MapZMax 900 mm",
    "",
    "/MACE/Analysis/AddMap Solenoid",
    "/MACE/Analysis/MapNBinX 423",
    "/MACE/Analysis/MapXMin -150 mm",
    "/MACE/Analysis/MapXMax 1965 mm",
    "/MACE/Analysis/MapNBinY 60",
    "/MACE/Analysis/MapYMin -150 mm",
    "/MACE/Analysis/MapYMax 150 mm",
    "/MACE/Analysis/MapNBinZ 160",
    "/MACE/Analysis/MapZMin 1000 mm",
    "/MACE/Analysis/MapZMax 1800 mm",
    "",
    "/Mustard/Analysis/FilePath SimDose_vis.root",
    "/Mustard/Analysis/FileMode RECREATE",
    "",

#if MUSTARD_USE_G4VIS

    "#############################################################################",
    "# Visualization settings",
    "#############################################################################",
    "",
    "/vis/open OGL",
    "",
    "/vis/viewer/set/autoRefresh false",
    "/vis/verbose errors",
    "",
    "/vis/drawVolume",
    "",
    "/vis/viewer/set/viewpointVector -1 0.5 0.5",
    "/vis/viewer/set/lightsVector -1 1 1",
    "#/vis/viewer/set/rotationStyle freeRotation",
    "/vis/viewer/set/projection p",
    "/vis/viewer/set/style s",
    "/vis/viewer/set/auxiliaryEdge false",
    "#/vis/viewer/set/lineSegmentsPerCircle 100",
    "/vis/viewer/zoom 2.5",
    "",
    "# Visibility",
    "/vis/geometry/set/visibility CDCCell             -1 false",
    "/vis/geometry/set/visibility CDCSuperLayer        0 false",
    "/vis/geometry/set/visibility ECALField             0 false",
    "/vis/geometry/set/visibility ECALPMCathode        0 false",
    "/vis/geometry/set/visibility ECALPMTCoupler        0 false",
    "/vis/geometry/set/visibility MMSField             0 false",
    "/vis/geometry/set/visibility SolenoidFieldS1      0 false",
    "/vis/geometry/set/visibility SolenoidFieldS2      0 false",
    "/vis/geometry/set/visibility SolenoidFieldS3      0 false",
    "/vis/geometry/set/visibility SolenoidFieldT1      0 false",
    "/vis/geometry/set/visibility SolenoidFieldT2      0 false",
    "",
    "# Colors",
    "/vis/geometry/set/colour Accelerator                   0     1     1     1     0.1",
    "/vis/geometry/set/colour AcceleratorField              0     1     1     1     0.05",
    "/vis/geometry/set/colour BeamDegrader                  0     1     1     1     0.1",
    "/vis/geometry/set/colour BeamMonitor                   0     1     1     1     0.1",
    "/vis/geometry/set/colour CDCBody                       0     1     1     1     0.01",
    "/vis/geometry/set/colour CDCCell                       0     1     1     1     0.005",
    "/vis/geometry/set/colour CDCFieldWire                  0     1     1     1     0.01",
    "/vis/geometry/set/colour CDCGas                        0     1     1     1     0.005",
    "/vis/geometry/set/colour CDCSenseLayer                 0     1     1     1     0.015",
    "/vis/geometry/set/colour CDCSenseWire                  0     1     1     1     0.01",
    "/vis/geometry/set/colour CDCSensitiveVolume            0     1     1     1     0.005",
    "/vis/geometry/set/colour CDCSuperLayer                 0     1     1     1     0.005",
    "/vis/geometry/set/colour Collimator                    0     1     1     1     0.01",
    "/vis/geometry/set/colour ECALCrystal                   0     1     1     1     0.1",
    "/vis/geometry/set/colour ECALField                     0     1     1     1     0.05",
    "/vis/geometry/set/colour ECALMagnet                    0     1     1     1     0.05",

    "/vis/geometry/set/colour ECALShield                    0     1     1     1     0.05",

    "/vis/geometry/set/colour ECALPMTCoupler                0     1     1     1     0.1",
    "/vis/geometry/set/colour ECALPMTShell                  0     1     1     1     0.05",
    "/vis/geometry/set/colour ECALPMTVacuum                 0     1     1     1     0.",
    "/vis/geometry/set/colour ECALMPPCWindow                0     1     1     1     0.2",
    "/vis/geometry/set/colour ECALMPPCCoupler               0     1     1     1     0.1",
    "/vis/geometry/set/colour ECALPMCathode                0     1     1     1     0.3",

    "/vis/geometry/set/colour MCP                           0     1     1     1     0.1",
    "/vis/geometry/set/colour MCPAnode                      0     1     1     1     0.1",
    "/vis/geometry/set/colour MCPChamber                    0     1     1     1     0.05",
    "/vis/geometry/set/colour MCPChamberPipe                0     1     1     1     0.05",
    "/vis/geometry/set/colour MCPChamberPipeVacuum          0     1     1     1     0.05",
    "/vis/geometry/set/colour MCPChamberVacuum              0     1     1     1     0.05",
    "/vis/geometry/set/colour MMSBeamPipe                   0     1     1     1     0.05",
    "/vis/geometry/set/colour MMSBeamPipeVacuum             0     1     1     1     0.01",
    "/vis/geometry/set/colour MMSField                      0     1     1     1     0.05",
    "/vis/geometry/set/colour MMSMagnet                     0     1     1     1     0.05",
    "/vis/geometry/set/colour MMSShield                     0     1     1     1     0.05",
    "/vis/geometry/set/colour ShieldingWall                 0     1     1     1     0.05",
    "/vis/geometry/set/colour SolenoidBeamPipeS1            0     1     1     1     0.1",
    "/vis/geometry/set/colour SolenoidBeamPipeS1Vacuum      0     1     1     1     0.01",
    "/vis/geometry/set/colour SolenoidBeamPipeS2            0     1     1     1     0.1",
    "/vis/geometry/set/colour SolenoidBeamPipeS2Vacuum      0     1     1     1     0.01",
    "/vis/geometry/set/colour SolenoidBeamPipeS3            0     1     1     1     0.1",
    "/vis/geometry/set/colour SolenoidBeamPipeS3Vacuum      0     1     1     1     0.01",
    "/vis/geometry/set/colour SolenoidBeamPipeT1            0     1     1     1     0.1",
    "/vis/geometry/set/colour SolenoidBeamPipeT1Vacuum      0     1     1     1     0.01",
    "/vis/geometry/set/colour SolenoidBeamPipeT2            0     1     1     1     0.1",
    "/vis/geometry/set/colour SolenoidBeamPipeT2Vacuum      0     1     1     1     0.01",
    "/vis/geometry/set/colour SolenoidFieldS1               0     1     1     1     0.05",
    "/vis/geometry/set/colour SolenoidFieldS2               0     1     1     1     0.05",
    "/vis/geometry/set/colour SolenoidFieldS3               0     1     1     1     0.05",
    "/vis/geometry/set/colour SolenoidFieldT1               0     1     1     1     0.05",
    "/vis/geometry/set/colour SolenoidFieldT2               0     1     1     1     0.05",
    "/vis/geometry/set/colour SolenoidS1                    0     1     1     1     0.05",
    "/vis/geometry/set/colour SolenoidS2                    0     1     1     1     0.05",
    "/vis/geometry/set/colour SolenoidS3                    0     1     1     1     0.05",
    "/vis/geometry/set/colour SolenoidShieldS1              0     1     1     1     0.1",
    "/vis/geometry/set/colour SolenoidShieldS2              0     1     1     1     0.1",
    "/vis/geometry/set/colour SolenoidShieldS3              0     1     1     1     0.1",
    "/vis/geometry/set/colour SolenoidShieldT1              0     1     1     1     0.1",
    "/vis/geometry/set/colour SolenoidShieldT2              0     1     1     1     0.1",
    "/vis/geometry/set/colour SolenoidT1                    0     1     1     1     0.05",
    "/vis/geometry/set/colour SolenoidT2                    0     1     1     1     0.05",
    "/vis/geometry/set/colour Target                        0     1     1     1     0.1",
    "/vis/geometry/set/colour TTC                           0     1     1     1     0.05",
    "/vis/geometry/set/colour World                         0     1     1     1     0.001",
    "",
    "/vis/scene/add/date",
    "/vis/scene/add/axes 0 0 0 10 cm",
    "/vis/scene/add/trajectories smooth #rich",
    "/vis/scene/add/hits",
    "",
    "/vis/filtering/trajectories/create/particleFilter",
    "/vis/filtering/trajectories/particleFilter-0/add mu+",
    "/vis/filtering/trajectories/particleFilter-0/add mu-",
    "/vis/filtering/trajectories/particleFilter-0/add muonium",
    "/vis/filtering/trajectories/particleFilter-0/add anti_muonium",
    "/vis/filtering/trajectories/particleFilter-0/add e+",
    "/vis/filtering/trajectories/particleFilter-0/add e-",
    "/vis/filtering/trajectories/particleFilter-0/add gamma",
    "/vis/filtering/trajectories/particleFilter-0/add opticalphoton",
    "/vis/filtering/trajectories/particleFilter-0/add neutron",
    "/vis/filtering/trajectories/particleFilter-0/add anti_neutron",
    "/vis/filtering/trajectories/particleFilter-0/add proton",
    "/vis/filtering/trajectories/particleFilter-0/add anti_proton",
    "/vis/filtering/trajectories/particleFilter-0/add pi+",
    "/vis/filtering/trajectories/particleFilter-0/add pi-",
    "/vis/filtering/trajectories/particleFilter-0/add pi0",
    "",
    "/vis/modeling/trajectories/create/drawByParticleID",
    "/vis/modeling/trajectories/drawByParticleID-0/default/setDrawAuxPts false",
    "/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsSize 2",
    "/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsSizeType screen",
    "/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsType dots",
    "/vis/modeling/trajectories/drawByParticleID-0/default/setDrawLine true",
    "/vis/modeling/trajectories/drawByParticleID-0/default/setLineWidth 2",
    "/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true",
    "/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSize 2",
    "/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSizeType screen",
    "/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsType dots",
    "",
    "/vis/modeling/trajectories/drawByParticleID-0/setRGBA muonium 1 0 1 1",
    "/vis/modeling/trajectories/drawByParticleID-0/setRGBA anti_muonium 1 0 1 1",
    "",
    "/vis/scene/endOfEventAction accumulate",
    "",
    "/vis/verbose warnings",
    "/vis/viewer/set/autoRefresh true",

#endif

    ""};

} // namespace MACE::SimDose
